### ISSUE TITLE
unable to pull "the image"

### ISSUE THREAD

**Issue by geojog** [gdsbook/book#101]
I tried "docker pull gdsbook/stack", but the resulted as follows: "Using default tag: latest
Error response from daemon: manifest for gdsbook/stack:latest not found: manifest unknown: manifest unknown"

Thank you for your assistance. db

**Comment by darribas** [comment]
Hello @geojog thanks for reaching out. We have a blog post pending to be written about this issue. We have two containers for you to use:

1. We develop the book on the [`gds_env`](https://darribas.org/gds_env/) and the current stable version, `5.0` supports the book. However, if you pull that image, the book contents will not be there, although you can donwload them.
1. We have a `Dockerfile` on the repository for Binder builds, which layers the materials on top of `gds_env`, but we don't deploy that to Docker Hub. However, if you want to build it locally, you can checkout the repository on your local machine, `cd` into its main folder, and run:

```shell
docker build -t gdsbook .
```
That'll create a container with `gds_py:5.0` and the book materials.

Feel free to reopen and follow up on this issue if you run into further problems, but I'll otherwise close it for now.
